package com.example.diyashop.model;

public enum ProductModel {

    ACCESSORIES,
    APPARELS, BAG_AND_PURSE, CHRISTMAS_AND_EASTER, FELT, KITCHEN_ITEMS, JEWELLERY,LOKTA_PAPER_CRAFTS,
    METAL, POTTERY, SHAWLS_SCARFS_AND_THROWS, WELLNESS, WOODEN,WOOLLEN,SOAP_AND_BARS,HEMP_AND_NETTLE;

    ;
    public enum SpecificEnum{
        //ACCESSORIES
        DOUBLE_SHEEP_WOOL_JAKART_SCARF,
        DOUBLE_WOOL_MUFFLER,
        THAILLI, OVAL_SHAPE_RINGS, SHEEP_WOOL_SCREEN_SHAWL,SILVER_CARVING_BANGLE, SILVER_CARVING_RING, SILVER_DRAGON_CARVING_BANGLE,SILVER_JAIL_LAPIS_STONE, WHITE_METAL_NECKLACE,WHITE_METAL_AKURA_WITH_STONE_RING,


       // APPARELS
        DHAKA_HALF_SHAWL, DHAKA_MUFFLER,HEAVY_YARN_COTTON_VISCOSE,
        // BAG_AND_PURSE
        COTTON_LAPTOP_BAG, COTTON_SHOPPING_BAG,DHAKA_SOCKS_POUCH,    DHAKA_BAG, HEAVY_YARN_COTTON_VISCOSE_PENCIL,

        //  CHRISTMAS_AND_EASTER
        BABY_HEN_DOLL, CHRISTMAS_DECORATION_BALL, CHRISTMAS_WOODEN_PAINTING_HANGING_BALL,FELT_EASTER_EGG,KNITTED_EASTER_EGG,RABBIT_WITH_CARROT,WOOD_PAINDED_HANGING_ANGEL,
        WOOD_PAINTED_HANGING_GLOVE, WOOD_PAINTED_HANGING_SANTA_SHOE,  WOOD_PAINTED_HANGING_SANTA, WOOD_PAINTED_HANGING_TREE,XMAS_HANGING_MAN,

        //FELT
        FELT_HEEL_SLIPPERS,  FELT_KEY_RING,FELT_LONG_HANDLE,FELT_ROUND_CUSHION,FELT_XMAS_HANGING_BIRD,FELT_US_COIN_PURS,

        // KITCHEN_ITEMS
        HAND_POT_HOLDER,HEART_SHAPE_POT_HOLDER, SQUARE_SHAPE_POT_HOLDER,
        //JEWELERY
        BRACELET_1,BRACELET_2,BRACELET_3, EAR_RINGS, GOSS_HAMMER_BANGLE,EARRINGS,SILVER_AKURA_LAPIS,SILVER_AKURA_LAPIS_STONE_RING, SILVER_CALLY_CARVING_BANGLE,SILVER_DEEP_CARVED_RING,SILVER_EAR_PIN,
        SILVER_HEAVY_CARVED_BANGLE,SILVER_JAIL_LAPIS_STONE_PENDANT,

        //LOKTA_PAPER_ITEMS
        COTTON_CLOTH_PASTE,COTTON_WOOD_DESIGN,DHAKA_ALL_OVER_PRINTED_SHOPPING_BAG,DHAKA_BORDER_PENCILE_HOLDER, DOODLING_DESIGN_NOTEBOOK,DOODLING_DESIGN_PHOTO_ALBUM,

        //METAL
        THADO_SINGING_BOWL,THADO_SINGING_BOWL_DESIGN,WHITE_METAL_NECKLACE_WITH_TURQUOISE_BEADS, SINGING_BOWL_SET,SINGING_BOWL_WITH_STANDT_SET,
        //POTTERY
        CERAMICS_CANDLE_STAND,CERAMIC_CUP,CERAMIC_FLOWER_VASE, CERAMIC_MUG, CERAMIC_PIG_FACE,CERAMIC_STONEWARE_BOWL_SMALL,CERAMIC_STONEWARE_BOWL_MEDIUM,CERAMIC_STONEWARE_BOWL_LARGE,
        CERAMIC_STONEWARE_TEA_POT, CERAMIC_STONEWARE_TEA_POT_MIX_DESIGN, CERAMIC_MADAL_FLOWER_VASE,CLAY_FLOWER_CEILING,CLAY_MANDALA_HANGING,NAGLO_DESIGN_BOWL,NAGLO_DESIGN_PLATE,
        STONEWARE_CERAMIC_MUG, STONEWARE_PLASTIC_DESIGN_FLOWER_VASE,
        //SHAWLS_SCARFS_AND_THROWS
        CASHMERE_SHAWL_HUNDERED_PERCENT,CASHMERE_V_NECT_LADIES_SWEATER_HUNDRED_PERCENT, JACQUARD_SHWAL_AND_THROW_HUNDERED_PERCENT, CASHMERE_BABY_BLANKET,CASHMERE_JALI_SHAWL,CASHMERE_KNITTING_STRIPE_MUFFLER,CASHMERE_LADIES_ROUND_NECT,CASHMERE_NATURAL_SHWAL,CASHMERE_STRIPE_MUFFLER,SHEEP_WOOL_CHECK_SHAWL,SHEEP_WOOL_HERRING_BONE,WOOL_JACQUARD_SHAWL,

        //WOODEN
        WOODEN_CLIP_LARGE,WOODEN_CLIP,WOODEN_CLIP_SMALL,WOODEN_CLIP_HOLDER, WOODEN_COMB_LARGE,WOODEN_COMB_SMALL,WOODEN_MEN_AND_WOMEN,WOODEN_MOBILE_STAND,

        //WOOLLEN
        WOOLLEN_EAR_HAT,BOB_MARLEY_CAP,

        //HEMP_UND_NETTLE
        HEMP_AND_COTTON_WALLET, HEMP_COIN_PURSE,HEMP_HAT,SILK_AND_HEMP_BAG,HEMP_PLUS_COTTON_BAG,
        HEMP_PURSE_COLORED_PATTERN,HEMP_PENCIL_CASE,
    }
}
