package com.example.diyashop.view;

public enum AdminOptionView {
    ADD_PRODUCT,
    RECIEPT,
    SEARCH,
    DAILY_EXPENDITURE, WEEKLY_EXPENDITURE,MONTHLY_EXPENDITURE,QUARTERLY_EXPENDITURE, HALF_YEARLY_EXPENDITURE,YEARLY_EXPENDITURE,
    STATE_OF_PRODUCTS,
    DAILY_VIEW, WEEKLY_VIEW, QUATERLY_VIEW, HALF_YEARLY_VIEW ,YEARLY_VIEW;
}
